= Beyond writing

For the most part we are producing documentation for delivery on the
web, which is a rich platform that allows for more than pure text. I
have already mentioned that images help break up the flow of walls of
text, but good images also help illustrate a complex topic. While advice
for creating video content is an entire subject in itself (maybe coming
soon), they are also worth considering for newer developers, who tend to
prefer them.

Taking things up a notch, but a lot of fun for developers, is creating
interactive documentation. This can mean anything from using the inbuilt
API explorer tools that are often part of API hosting platforms such as
https://apiary.io[Apiary], https://www.getpostman.com/[Postman] or
https://swagger.io/tools/swaggerhub/[SwaggerHub], or using tools such as
https://jsfiddle.net/[JSFiddle] and https://repl.it[Repl.it] to creating
your own custom solution. The interactive approach (in any form) is one
of the best ways to explain complex tools and what’s possible with them,
but bear in mind that someone with the right skill set needs to maintain
them, especially if you create your own.